[phases.setup]
nixPkgs = [
  "python313",
  "python313Packages.pip",
  "jdk17",
  "lua",
  "lua51Packages.lua",
  "lua52",
  "lua53",
  "lua54"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
